#!/bin/sh


FILE1=/tmp/tzone1-$$
FILE2=/tmp/tzone2-$$
ERROR=/tmp/err-$$

GETTEXT="gettext -d SelectTZ-ES"

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

end() {

	rm -f $FILE $FILE2 $ERROR
	exit
}

while true
do
	$DIALOG --inputbox "`$GETTEXT \"Enter location (Continent/City):\"`" 8 35 2> $FILE1 || end

	if cat $FILE1 | timezone > $FILE2 2> $ERROR
	then
		MSG="`$GETTEXT \"Result:\"` `cat $FILE2`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 7 20 || end
	else
		MSG="`$GETTEXT \"Error:\"`\\n\\n`cat $ERROR`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --YESNO "$MSG" 10 35 || end
	fi
done



