#!/bin/sh

if [ -r ~/.calc.conf ]
then
	. ~/.calc.conf
elif [ -r /etc/calc.conf ]
then
	. /etc/calc.conf
fi

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

while true
do
	$DIALOG --inputbox "`$GETTEXT \"Enter expression:\"`" 8 35 2> $FILE1 || end
	if cat $FILE1 | $CALC > $FILE2 2>$ERROR
	then
		MSG="`$GETTEXT \"Result:\"` `cat $FILE2`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 7 20 || end
	else
		MSG="`$GETTEXT \"Error:\"`\\n\\n`cat $ERROR`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 10 35 || end
	fi
done
